[package]
name = "lol-classic-meta"
version = "1.0.1"
description = "LoL Classic Meta - Real Top 5 Meta by vamp9"
authors = ["vamp9"]
edition = "2021"

[lib]
name = "lol_classic_meta_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }
chrono = { version = "0.4", features = ["serde"] }
